"""colorkit.stylize — the STYLIZE stage (Stage 3) of the headless color engine.

This module owns the *creative look* layer that sits on top of an
already-neutralized (corrected + matched) image or shot. It deliberately does
NOT measure or correct pixels — that is the job of ``measure.py`` / ``correct.py``.
Here we only apply a pre-authored look, expressed either as a 3D LUT (``.cube``)
or as a lightweight split-tone.

Two parallel surfaces, mirroring the rest of the package:

* **Video path (deterministic, ffmpeg):** ``ffmpeg_lut_filter`` and
  ``ffmpeg_splittone_filter`` return filtergraph *strings*. The CLI
  (``color.py``) composes one constant correction filter + (optionally) one
  uniform look filter per shot, so the look is applied identically to every
  frame of the clip — no flicker, no per-frame divergence.
* **Still path (pixel, colour-science):** ``apply_look_image`` applies a
  ``.cube`` LUT to a single BGR array using tetrahedral interpolation, matching
  the ``lut3d=interp=tetrahedral`` ffmpeg apply so a still preview looks like
  the video grade.

LUT registry
------------
``LOOKS`` maps a friendly look name -> absolute path of its ``.cube`` file under
``colorkit/luts/``. The cube files themselves are generated by ``luts.py``
(stdlib-only); this module only references them by path and never imports
``luts.py`` (so a missing/ungenerated cube degrades to a clear error at apply
time, not an import-time failure).

Design rules honored:
* Tetrahedral interpolation everywhere (matches the ffmpeg apply and is the
  standard for film LUTs).
* BGR<->RGB and 0..255<->0..1 conversions are handled internally so callers
  pass and receive ordinary OpenCV BGR arrays.
* No network, no GPL deps, outputs never leave the engine here (this module
  returns strings / arrays; only ``color.py`` writes to ``out/``).
"""

from __future__ import annotations

import os
from typing import Dict, List, Sequence, Tuple

import numpy as np

__all__ = [
    "LUTS_DIR",
    "LOOKS",
    "list_looks",
    "look_path",
    "ffmpeg_lut_filter",
    "apply_look_image",
    "bake_look_at_opacity",
    "ffmpeg_splittone_filter",
    # cinematic look-stack (optical film effects, still path)
    "LOOK_STACKS",
    "look_stack",
    "apply_halation_image",
    "apply_grain_image",
    "apply_vignette_image",
    "apply_look_stack_image",
    # cinematic look-stack (VIDEO path: deterministic ffmpeg filtergraph segments + plate bakers)
    "optical_stack_plan",
    "bake_grain_plate",
    "bake_vignette_mask",
    "ffmpeg_halation_segment",
    "ffmpeg_grain_segment",
    "ffmpeg_vignette_segment",
]


# --------------------------------------------------------------------------- #
# LUT registry
# --------------------------------------------------------------------------- #

#: Absolute path to the directory holding the generated ``.cube`` look files.
#: Resolved relative to *this* file so it is stable regardless of the caller's
#: working directory.
LUTS_DIR: str = os.path.join(os.path.dirname(os.path.abspath(__file__)), "luts")


def _cube(name: str) -> str:
    """Absolute path of the ``<name>.cube`` file inside :data:`LUTS_DIR`."""
    return os.path.join(LUTS_DIR, f"{name}.cube")


#: Registry of named looks -> absolute ``.cube`` path. The five generators live
#: in ``luts.py``; their output filenames are ``<name>.cube``. Keys here are the
#: exact ``--look`` values accepted by the CLI.
LOOKS: Dict[str, str] = {
    "neutral_correct": _cube("neutral_correct"),
    "warm_interview": _cube("warm_interview"),
    "teal_orange": _cube("teal_orange"),
    "kodak_2383_style": _cube("kodak_2383_style"),
    "fuji_style": _cube("fuji_style"),
    # fresh film looks (2026-06-24)
    "golden_hour": _cube("golden_hour"),
    "moody_blue": _cube("moody_blue"),
    "bleach_bypass": _cube("bleach_bypass"),
    "clean_pop": _cube("clean_pop"),
    "portra_style": _cube("portra_style"),
}


def list_looks() -> List[str]:
    """Return the registered look names, sorted for stable CLI display."""
    return sorted(LOOKS.keys())


def look_path(name: str) -> str:
    """Resolve a look *name* to its absolute ``.cube`` path.

    Parameters
    ----------
    name
        A key of :data:`LOOKS` (e.g. ``"teal_orange"``).

    Returns
    -------
    str
        Absolute path to the look's ``.cube`` file.

    Raises
    ------
    KeyError
        If *name* is not a registered look. The message lists the valid names
        so the CLI can surface a useful error.
    """
    try:
        return LOOKS[name]
    except KeyError as exc:  # pragma: no cover - trivial
        valid = ", ".join(list_looks())
        raise KeyError(
            f"Unknown look {name!r}. Registered looks: {valid}"
        ) from exc


# --------------------------------------------------------------------------- #
# FFmpeg filter strings (video apply — constant/uniform across all frames)
# --------------------------------------------------------------------------- #

def ffmpeg_lut_filter(cube_path: str, *, expect_dir: "str | None" = None) -> str:
    """Build the ffmpeg ``lut3d`` filter string (bare-filename) for a 3D LUT apply.

    Uses tetrahedral interpolation (the film-LUT standard, and what
    :func:`apply_look_image` uses) so the still and video paths match.

    Parameters
    ----------
    cube_path
        Path to an Iridas ``.cube`` file, or a registered look *name* (resolved via
        :data:`LOOKS`). Only its BARE FILENAME is emitted -- see Notes.
    expect_dir
        If given, the cube's directory MUST equal ``expect_dir`` (the directory ffmpeg will be run
        from) and the file must exist there, else ``ValueError`` / ``FileNotFoundError`` is raised.
        Pass this from the render loop so a mis-staged cube fails LOUDLY here instead of producing a
        filter ffmpeg can't open. ``color.py`` passes ``expect_dir=lut_dir``.

    Returns
    -------
    str
        A bare-filename lut3d filter, e.g. ``lut3d=interp=tetrahedral:file=teal_orange.cube``.

    Notes
    -----
    Emits the cube's BARE FILENAME, never an absolute path. The original motivation is a Windows
    ffmpeg bug -- the ``lut3d`` filtergraph parser rejects absolute Windows paths (the drive colon
    is read as an option separator and spaces break it; no escaping/quoting we tried -- ``C\\:``,
    single-quoting, ``\\ `` -- got past it). The fix is CROSS-PLATFORM and now load-bearing on
    EVERY OS (do not "simplify" it away on Linux/mac): the caller stages every cube used in one
    render into a single directory and runs ffmpeg with ``cwd`` set there (see
    :func:`io_utils.run_ffmpeg`'s ``cwd`` arg), so the bare filename resolves. The result is one
    comma-joined element of a per-shot filtergraph, placed AFTER the correction filter.
    """
    # Allow callers to pass a look name instead of a path.
    if cube_path in LOOKS:
        cube_path = LOOKS[cube_path]
    abspath = os.path.abspath(cube_path)
    if expect_dir is not None:
        want = os.path.abspath(expect_dir)
        if os.path.normcase(os.path.dirname(abspath)) != os.path.normcase(want):
            raise ValueError(
                f"ffmpeg_lut_filter: cube {abspath!r} is not in the expected cwd dir {want!r}; "
                "stage it there first -- lut3d needs a bare filename resolved from ffmpeg's cwd."
            )
        if not os.path.isfile(abspath):
            raise FileNotFoundError(f"ffmpeg_lut_filter: staged cube not found: {abspath}")
    # Bare filename only -- see Notes. The caller runs ffmpeg with cwd = the cube's directory.
    return f"lut3d=interp=tetrahedral:file={os.path.basename(abspath)}"


def _clamp01(values: Sequence[float]) -> Tuple[float, float, float]:
    """Clamp a 3-tuple of RGB values into ``[0, 1]`` and coerce to floats."""
    out = []
    for v in values:
        f = float(v)
        if f < 0.0:
            f = 0.0
        elif f > 1.0:
            f = 1.0
        out.append(f)
    if len(out) != 3:
        raise ValueError(f"expected 3 RGB components, got {len(out)}: {values!r}")
    return out[0], out[1], out[2]


def ffmpeg_splittone_filter(
    shadow_rgb: Sequence[float],
    highlight_rgb: Sequence[float],
    strength: float = 0.5,
) -> str:
    """Build an ffmpeg ``colorbalance`` filter that split-tones a clip.

    Split-toning pushes shadows toward one hue and highlights toward another —
    the classic "teal shadows, warm highlights" cinematic move. ``colorbalance``
    exposes per-range (shadow / midtone / highlight) R/G/B shifts in
    ``[-1, 1]``; we map the *direction* of each target color into those shifts,
    scaled by *strength*.

    Parameters
    ----------
    shadow_rgb
        Target tint for the shadow range, RGB in ``0..1``. The push is computed
        from each channel's deviation around mid-grey (0.5), so e.g.
        ``(0.0, 0.4, 0.5)`` pushes shadows toward teal.
    highlight_rgb
        Target tint for the highlight range, RGB in ``0..1``.
    strength
        Overall intensity multiplier in ``[0, 1]`` (default ``0.5``). Keeps the
        effect tasteful; ``1.0`` is an aggressive grade.

    Returns
    -------
    str
        e.g. ``colorbalance=rs=-0.25:gs=-0.05:bs=0.0:rh=0.2:gh=0.05:bh=-0.15:pl=1``

    Notes
    -----
    ``pl=1`` preserves lightness so the tint shifts hue without crushing or
    blowing exposure. Midtones are intentionally left neutral (``rm/gm/bm``
    default to 0) so split-toning protects mid-tone skin.
    """
    sr, sg, sb = _clamp01(shadow_rgb)
    hr, hg, hb = _clamp01(highlight_rgb)
    s = float(strength)
    if s < 0.0:
        s = 0.0
    elif s > 1.0:
        s = 1.0

    # Convert an absolute target color (0..1, centered at mid-grey) into a
    # signed colorbalance shift in [-1, 1]: (channel - 0.5) * 2 * strength.
    def _shift(c: float) -> float:
        return round((c - 0.5) * 2.0 * s, 4)

    rs, gs, bs = _shift(sr), _shift(sg), _shift(sb)
    rh, gh, bh = _shift(hr), _shift(hg), _shift(hb)

    return (
        f"colorbalance="
        f"rs={rs}:gs={gs}:bs={bs}:"
        f"rh={rh}:gh={gh}:bh={bh}:"
        f"pl=1"
    )


# --------------------------------------------------------------------------- #
# Still apply (pixel path — colour-science 3D LUT, tetrahedral)
# --------------------------------------------------------------------------- #

def _to_float_rgb01(bgr: np.ndarray) -> Tuple[np.ndarray, bool]:
    """Convert an OpenCV BGR array to float RGB in ``0..1``.

    Returns the RGB float array plus a flag recording whether the input was an
    integer (uint8/uint16) image so the result can be converted back to the
    same dtype.
    """
    arr = np.asarray(bgr)
    if arr.ndim != 3 or arr.shape[2] < 3:
        raise ValueError(
            f"apply_look_image expects an H x W x 3 BGR array, got shape {arr.shape}"
        )

    was_integer = np.issubdtype(arr.dtype, np.integer)
    if was_integer:
        # Scale by the dtype max so uint8 -> /255, uint16 -> /65535.
        info = np.iinfo(arr.dtype)
        scale = float(info.max)
        rgb = arr[..., 2::-1].astype(np.float64) / scale  # BGR->RGB + normalize
    else:
        # Already float; assume it is (or should be) in 0..1.
        rgb = arr[..., 2::-1].astype(np.float64)

    return np.ascontiguousarray(rgb), was_integer


def _from_float_rgb01(rgb: np.ndarray, was_integer: bool, like: np.ndarray) -> np.ndarray:
    """Convert a float RGB ``0..1`` array back to a BGR array matching *like*.

    If the original input was integer, the output is re-quantized to the same
    integer dtype (clamped to ``[0, max]``); otherwise a float BGR array in
    ``0..1`` is returned.
    """
    rgb = np.clip(rgb, 0.0, 1.0)
    bgr = rgb[..., ::-1]  # RGB -> BGR
    if was_integer:
        info = np.iinfo(like.dtype)
        scaled = bgr * float(info.max)
        # Round-half-up then clamp before casting to avoid truncation bias.
        out = np.clip(np.rint(scaled), 0, info.max).astype(like.dtype)
    else:
        out = bgr.astype(like.dtype, copy=False)
    return np.ascontiguousarray(out)


def apply_look_image(bgr: np.ndarray, cube_path: str, opacity: float = 1.0) -> np.ndarray:
    """Apply a ``.cube`` 3D LUT to a single BGR image (still path), at ``opacity`` in [0,1].

    Mirrors the video ``lut3d=interp=tetrahedral`` apply so a still preview
    matches the graded clip. Handles BGR<->RGB ordering and 0..255<->0..1
    scaling internally, so callers pass and receive plain OpenCV BGR arrays.

    ``opacity`` < 1.0 blends the graded result back toward the input (``out =
    in*(1-opacity) + look*opacity``). Pro practice (confirmed across the analyzed
    masterclasses) is to run a creative look UNDER the grade at ~0.5-0.8, never
    100%, so it reads as a tasteful look rather than a one-tap filter.

    Parameters
    ----------
    bgr
        OpenCV image as an ``H x W x 3`` BGR array. ``uint8``/``uint16``
        integer images and float images (assumed already in ``0..1``) are both
        accepted; the returned array uses the same dtype.
    cube_path
        A registered look *name* (key of :data:`LOOKS`) or a path to an Iridas
        ``.cube`` file.

    Returns
    -------
    numpy.ndarray
        The stylized BGR image, same shape and dtype as the input.

    Raises
    ------
    FileNotFoundError
        If the resolved ``.cube`` file does not exist (e.g. ``luts.py`` has not
        been run yet to generate the look library).
    KeyError
        If *cube_path* is a name that is not a registered look.

    Notes
    -----
    ``colour.io.read_LUT`` may return a ``LUT3D``, ``LUT3x1D``, ``LUT1D`` or a
    ``LUTSequence`` depending on the file; all of these expose ``.apply``. We
    pass the tetrahedral interpolator only to 3D LUTs (1D/3x1D LUTs do not take
    an interpolator); for those and for ``LUTSequence`` we fall back to the
    object's default ``apply`` to stay compatible.
    """
    # Import colour lazily so importing this module never pulls in the heavy
    # colour-science dependency (and never triggers cv2/numpy load-order issues
    # on the OneDrive disk) unless a still is actually being stylized.
    import colour
    from colour.io.luts import LUT3D
    from colour.algebra import table_interpolation_tetrahedral

    # Resolve a look name to its path; otherwise use the given path as-is.
    if cube_path in LOOKS:
        cube_path = LOOKS[cube_path]
    cube_path = os.path.abspath(cube_path)
    if not os.path.isfile(cube_path):
        raise FileNotFoundError(
            f"LUT file not found: {cube_path}. "
            "Generate the look library first (python -m colorkit.luts --all)."
        )

    rgb, was_integer = _to_float_rgb01(bgr)

    lut = colour.io.read_LUT(cube_path)

    # 3D LUTs accept a tetrahedral interpolator; other LUT kinds / sequences do
    # not, so only pass it where it is valid.
    if isinstance(lut, LUT3D):
        graded = lut.apply(rgb, interpolator=table_interpolation_tetrahedral)
    else:
        graded = lut.apply(rgb)

    graded = np.asarray(graded, dtype=np.float64)
    op = float(min(max(opacity, 0.0), 1.0))
    if op < 1.0:
        graded = rgb * (1.0 - op) + graded * op  # blend toward the input (look under the grade)
    return _from_float_rgb01(graded, was_integer, np.asarray(bgr))


def bake_look_at_opacity(cube_path: str, opacity: float, dst_cube: str) -> str:
    """Bake an opacity-reduced variant of a look ``.cube`` (lerp identity->look by ``opacity``).

    Reads an Iridas ``.cube`` (R-fastest, as ``colorkit.luts.write_cube`` writes) and writes a new
    cube whose every entry is ``identity*(1-opacity) + look*opacity``, where ``identity`` is the
    grid sample itself. Applying THIS cube via ``lut3d`` is identical to applying the look at reduced
    opacity, but stays a single constant per-shot transform (flicker-free) and reuses the existing
    bare-filename/cwd staging. ``opacity`` is clamped to [0,1]; at 1.0 the look is unchanged.
    """
    import os

    if cube_path in LOOKS:
        cube_path = LOOKS[cube_path]
    op = float(min(max(opacity, 0.0), 1.0))

    size = None
    triplets: List[Tuple[float, float, float]] = []
    with open(cube_path, "r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            s = line.strip()
            if not s or s.startswith("#") or s.startswith("TITLE") or s.startswith("DOMAIN"):
                continue
            if s.upper().startswith("LUT_3D_SIZE"):
                size = int(s.split()[-1])
                continue
            parts = s.split()
            if len(parts) == 3:
                try:
                    triplets.append((float(parts[0]), float(parts[1]), float(parts[2])))
                except ValueError:
                    continue
    if size is None or len(triplets) != size ** 3:
        raise ValueError(f"bake_look_at_opacity: {cube_path} not a parseable size^3 cube "
                         f"(size={size}, entries={len(triplets)})")

    denom = float(size - 1)
    out_lines = [
        f"# opacity {op:.3f} variant of {os.path.basename(cube_path)} (identity->look lerp).",
        f"LUT_3D_SIZE {size}",
    ]
    # R-fastest order: index i -> ri=i%size, gi=(i//size)%size, bi=i//(size*size).
    for i, (lr, lg, lb) in enumerate(triplets):
        ri = i % size
        gi = (i // size) % size
        bi = i // (size * size)
        idr, idg, idb = ri / denom, gi / denom, bi / denom
        orr = idr * (1.0 - op) + lr * op
        ogg = idg * (1.0 - op) + lg * op
        obb = idb * (1.0 - op) + lb * op
        out_lines.append(f"{orr:.6f} {ogg:.6f} {obb:.6f}")
    from pathlib import Path
    dst = Path(dst_cube)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("\n".join(out_lines) + "\n", encoding="ascii", newline="\n")
    return str(dst)


# --------------------------------------------------------------------------- #
# Convenience: in-Python split-tone for stills (mirrors the ffmpeg version)
# --------------------------------------------------------------------------- #

def apply_splittone_image(
    bgr: np.ndarray,
    shadow_rgb: Sequence[float],
    highlight_rgb: Sequence[float],
    strength: float = 0.5,
) -> np.ndarray:
    """Apply a luminance-weighted split-tone to a still BGR image.

    Pixel-space counterpart of :func:`ffmpeg_splittone_filter` for the still
    preview path. Shadows are blended toward *shadow_rgb*, highlights toward
    *highlight_rgb*, with the blend weight driven by per-pixel luminance so
    midtones stay closest to neutral.

    Parameters
    ----------
    bgr
        ``H x W x 3`` BGR array (``uint8``/``uint16`` or float in ``0..1``).
    shadow_rgb, highlight_rgb
        Target tints, RGB in ``0..1``.
    strength
        Intensity in ``[0, 1]`` (default ``0.5``).

    Returns
    -------
    numpy.ndarray
        The split-toned BGR image, same shape and dtype as the input.
    """
    rgb, was_integer = _to_float_rgb01(bgr)
    sr = np.asarray(_clamp01(shadow_rgb), dtype=np.float64)
    hr = np.asarray(_clamp01(highlight_rgb), dtype=np.float64)
    s = float(min(max(strength, 0.0), 1.0))

    # Rec.709 luma as the shadow/highlight selector.
    luma = (
        0.2126 * rgb[..., 0]
        + 0.7152 * rgb[..., 1]
        + 0.0722 * rgb[..., 2]
    )[..., None]

    # Shadow weight peaks at black, highlight weight peaks at white; both
    # vanish at mid-grey so midtones are protected. Scaled by strength.
    shadow_w = (1.0 - luma) * s
    highlight_w = luma * s

    # Tint pushes the image toward (target - current) in the weighted regions.
    graded = rgb.copy()
    graded += shadow_w * (sr[None, None, :] - rgb)
    graded += highlight_w * (hr[None, None, :] - rgb)

    return _from_float_rgb01(graded, was_integer, np.asarray(bgr))


# --------------------------------------------------------------------------- #
# Cinematic look-STACK: optical film effects (still path)                      #
# --------------------------------------------------------------------------- #
# A "look" = its color cube (tint/split-tone/DENSITY, baked in luts.py) PLUS an
# ordered stack of SPATIAL effects applied AFTER it: halation -> grain -> vignette.
# These are spatial, not color, so they live here (not in the .cube). Each is
# DETERMINISTIC => flicker-safe. The video path (color.py) applies matching ffmpeg
# filters. Density is ALREADY baked into the cube, so it carries to both paths and
# is NOT repeated here. Recipes grounded in the masterclass research + an adversarial
# verify (docs/research/color-masterclass): halation/vignette in linear-ish light,
# grain in the encoded/Overlay domain (the one correctly display-domain op).


def _gauss(arr, sigma):
    """Gaussian blur via cv2 (FIR; the still preview ~approximates ffmpeg's IIR gblur on video)."""
    import cv2
    if sigma <= 0:
        return arr
    return cv2.GaussianBlur(arr, (0, 0), float(sigma))


def apply_halation_image(bgr, knee: float = 0.75, strength: float = 0.5,
                         red_weight=(1.0, 0.35, 0.20), sigma_frac: float = 0.012) -> np.ndarray:
    """Red-weighted highlight bloom (HALATION) composited in LINEAR light.

    linearize -> top-(~20%) luma mask (flat below ``knee``) -> red-weighted highlight energy ->
    Gaussian blur -> SCREEN in linear -> encode. Demonstrated knee 0.75 / Screen (Mostyn); the red
    weighting models the stock's back red-dye layer scattering. Pure spatial op => flicker-safe.
    """
    from . import tonemap as tm
    rgb, was_int = _to_float_rgb01(bgr)
    lin = tm.srgb_eotf(rgb)
    L = tm.luminance(lin)
    m = np.clip((L - float(knee)) / max(1e-6, 1.0 - float(knee)), 0.0, 1.0) ** 2
    rw = np.asarray(red_weight, dtype=np.float64)
    src = (lin * m[..., None] * rw).astype(np.float32)
    sigma = max(1.0, float(sigma_frac) * lin.shape[0])
    glow = np.clip(_gauss(src, sigma).astype(np.float64) * float(strength), 0.0, 1.0)
    out = 1.0 - (1.0 - lin) * (1.0 - glow)  # Screen, in linear
    return _from_float_rgb01(tm.srgb_oetf(out), was_int, np.asarray(bgr))


def apply_vignette_image(bgr, size: float = 0.55, aspect: float = 0.78,
                         softness: float = 0.30, strength: float = 0.20) -> np.ndarray:
    """Feathered ELLIPTICAL luma falloff darkening the edges (encoded domain; matches the ffmpeg geq).

    A radial smoothstep multiplier centred on the frame; ``aspect`` makes it oval, ``size`` is where the
    falloff starts, ``softness`` its feather width, ``strength`` the max darkening (keep subtle ~0.15-0.25
    to avoid haloing). Deterministic => flicker-safe.
    """
    rgb, was_int = _to_float_rgb01(bgr)
    h, w = rgb.shape[:2]
    ys, xs = np.mgrid[0:h, 0:w]
    nx = (xs - w / 2.0) / (0.5 * w)
    ny = (ys - h / 2.0) / (0.5 * h * max(1e-6, aspect))
    r = np.hypot(nx, ny)
    t = np.clip((r - float(size)) / max(1e-6, float(softness)), 0.0, 1.0)
    fall = t * t * (3.0 - 2.0 * t)  # smoothstep feather
    v = (1.0 - float(strength) * fall)[..., None]
    return _from_float_rgb01(rgb * v, was_int, np.asarray(bgr))


def apply_grain_image(bgr, strength: float = 0.38, size: float = 0.357,
                      seed: int = 12345) -> np.ndarray:
    """Monochrome film GRAIN: a DETERMINISTIC seeded static plate, Overlay-blended, shadow/mid-weighted.

    A seeded Gaussian noise plate (so it is reproducible and, as a static plate, flicker-free) is
    low-passed by ``size`` (grain correlation length), then composited via Overlay and weighted by luma
    so shadows/mids carry grain and highlights stay clean (Mullins shadow 0.605 > mid ~0.30 > hi 0).
    Demonstrated size 0.357 / strength 0.380, monochrome (sat 0). The masterclass-correct method --
    NOT ffmpeg's temporal ``noise`` filter, which regenerates per frame and FLICKERS.
    """
    rgb, was_int = _to_float_rgb01(bgr)
    h, w = rgb.shape[:2]
    plate = np.random.RandomState(int(seed)).standard_normal((h, w)).astype(np.float32)
    plate = _gauss(plate, max(0.4, float(size) * 2.0))  # grain SIZE -> correlation length
    plate = plate / (float(plate.std()) or 1.0)         # renormalize variance after the low-pass
    amp = float(strength) * 0.12
    g = np.clip(0.5 + plate * amp, 0.0, 1.0)[..., None]
    base = rgb
    overlay = np.where(base < 0.5, 2.0 * base * g, 1.0 - 2.0 * (1.0 - base) * (1.0 - g))
    L = 0.2126 * base[..., 0] + 0.7152 * base[..., 1] + 0.0722 * base[..., 2]
    wgt = (0.605 * (1.0 - L))[..., None]                # luma weight: shadows>mids>>highlights
    return _from_float_rgb01(base + (overlay - base) * wgt, was_int, np.asarray(bgr))


#: Which looks carry which optical effects (the cinematic stack). A look NOT listed (or mapped to {})
#: is color-only -- byte-identical to the pre-stack behavior. Strengths are tuned to read UNDER the
#: grade; ``apply_look_stack_image`` further scales them by the look opacity.
LOOK_STACKS: Dict[str, dict] = {
    "kodak_2383_style": {"halation": {"strength": 0.55}, "grain": {"strength": 0.40}},
    "portra_style":     {"halation": {"strength": 0.40}, "grain": {"strength": 0.28},
                         "vignette": {"strength": 0.14}},
    "golden_hour":      {"halation": {"strength": 0.45}, "grain": {"strength": 0.22}},
    "fuji_style":       {"grain": {"strength": 0.28}},
    "moody_blue":       {"grain": {"strength": 0.34}, "vignette": {"strength": 0.22}},
    "teal_orange":      {"halation": {"strength": 0.35}, "vignette": {"strength": 0.18}},
    "bleach_bypass":    {"grain": {"strength": 0.45}},
    "warm_interview":   {"halation": {"strength": 0.28}},
    "clean_pop":        {},   # crisp, modern digital -> no optical effects
    "neutral_correct":  {},
}

_STACK_ORDER = ("halation", "grain", "vignette")
_STACK_FNS = {
    "halation": apply_halation_image,
    "grain": apply_grain_image,
    "vignette": apply_vignette_image,
}


def look_stack(name: str) -> dict:
    """Return the optical-effect spec for a look name ({} if none/color-only)."""
    return LOOK_STACKS.get(name, {})


def apply_look_stack_image(bgr, cube_path_or_name: str, opacity: float = 1.0,
                           *, stack_name: "str | None" = None) -> np.ndarray:
    """Apply the look color cube at ``opacity`` then its ordered optical stack (halation->grain->vignette).

    The cube blend handles the COLOR look (under the grade at ``opacity``); the spatial effects layer on
    top in the fixed stack order, each scaled by ``opacity`` so the whole look fades together. A look with
    no stack entry is exactly :func:`apply_look_image` (byte-identical to the pre-stack behavior).
    """
    out = apply_look_image(bgr, cube_path_or_name, opacity=opacity)
    name = stack_name if stack_name is not None else (
        cube_path_or_name if cube_path_or_name in LOOKS else None)
    for eff, params in optical_stack_plan(name, opacity):
        out = _STACK_FNS[eff](out, **params)
    return out


# --------------------------------------------------------------------------- #
# Cinematic look-STACK: optical film effects (VIDEO path)                      #
# --------------------------------------------------------------------------- #
# The still path above applies the optical stack pixel-by-pixel; the VIDEO path must apply the SAME
# effects inside the per-shot ffmpeg filtergraph (color.py), constant for every frame of the clip so
# it stays flicker-free. Two surfaces are provided:
#   * plate BAKERS (bake_grain_plate / bake_vignette_mask) write a deterministic, seeded plate/mask
#     image ONCE per render; the filtergraph overlay-/multiply-blends that STATIC image onto every
#     frame -- never ffmpeg's temporal ``noise`` (which regenerates per frame = flicker).
#   * filtergraph SEGMENT builders (ffmpeg_*_segment) return a chain fragment wired by input/output
#     labels, mirroring the still math: halation = red-weighted highlight bloom SCREENED in linear
#     light; grain = monochrome shadow-weighted overlay on luma; vignette = elliptical multiply in RGB.
# ``optical_stack_plan`` resolves a look's stack into ordered (effect, params) with strength faded by
# the look opacity -- the SAME scaling ``apply_look_stack_image`` uses, so still and video agree.


def optical_stack_plan(name: "str | None", opacity: float) -> List[Tuple[str, dict]]:
    """Resolve a look's optical stack into an ordered ``[(effect, params), ...]`` list.

    Each effect's ``strength`` is scaled by ``opacity`` (mirroring
    :func:`apply_look_stack_image`'s per-effect fade), so the video path produces the same intensity
    as the still preview. Returns ``[]`` for a color-only look (no stack) or an unknown name.
    """
    spec = LOOK_STACKS.get(name or "", {})
    op = float(min(max(opacity, 0.0), 1.0))
    plan: List[Tuple[str, dict]] = []
    for eff in _STACK_ORDER:
        if eff in spec:
            params = dict(spec[eff] or {})
            if "strength" in params:
                params["strength"] = float(params["strength"]) * op
            plan.append((eff, params))
    return plan


def _fg(x: float) -> str:
    """Compact float for embedding in an ffmpeg filtergraph (no trailing zeros, no exponent surprises)."""
    return f"{float(x):.6g}"


def bake_grain_plate(dst_png: str, width: int, height: int, strength: float = 0.38,
                     size: float = 0.357, seed: int = 12345) -> str:
    """Bake a DETERMINISTIC seeded film-grain plate (grayscale PNG, centered on mid-grey 128).

    Identical plate math to :func:`apply_grain_image`: seeded ``N(0,1)`` -> low-pass by the grain
    ``size`` (correlation length) -> renormalize variance -> ``amp = strength*0.12`` -> ``0.5 +
    plate*amp`` clipped to [0,1] -> 8-bit. The video filtergraph overlay-blends THIS one static plate
    onto every frame of every shot, so grain is flicker-free by construction. ``width``/``height`` are
    the delivery (post-scale) frame size. Returns ``dst_png``.
    """
    import cv2
    from pathlib import Path
    w, h = int(width), int(height)
    plate = np.random.RandomState(int(seed)).standard_normal((h, w)).astype(np.float32)
    plate = cv2.GaussianBlur(plate, (0, 0), max(0.4, float(size) * 2.0))  # grain SIZE -> correlation length
    plate = plate / (float(plate.std()) or 1.0)                            # renormalize after low-pass
    amp = float(strength) * 0.12
    g = np.clip(0.5 + plate * amp, 0.0, 1.0)
    out = np.clip(g * 255.0 + 0.5, 0, 255).astype(np.uint8)
    Path(dst_png).parent.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(dst_png), out)
    return str(dst_png)


def bake_vignette_mask(dst_png: str, width: int, height: int, strength: float = 0.20,
                       size: float = 0.55, aspect: float = 0.78, softness: float = 0.30) -> str:
    """Bake the vignette MULTIPLIER mask (grayscale PNG; pixel value = ``v*255``, ``v = 1 - strength*fall``).

    The elliptical smoothstep falloff is identical to :func:`apply_vignette_image`, so the video
    multiply-blend (``base*mask/255 == base*v``) reproduces the still's ``rgb*v`` exactly.
    ``width``/``height`` are the delivery (post-scale) frame size. Returns ``dst_png``.
    """
    import cv2
    from pathlib import Path
    w, h = int(width), int(height)
    ys, xs = np.mgrid[0:h, 0:w]
    nx = (xs - w / 2.0) / (0.5 * w)
    ny = (ys - h / 2.0) / (0.5 * h * max(1e-6, float(aspect)))
    r = np.hypot(nx, ny)
    t = np.clip((r - float(size)) / max(1e-6, float(softness)), 0.0, 1.0)
    fall = t * t * (3.0 - 2.0 * t)  # smoothstep feather
    v = 1.0 - float(strength) * fall
    out = np.clip(v * 255.0 + 0.5, 0, 255).astype(np.uint8)
    Path(dst_png).parent.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(dst_png), out)
    return str(dst_png)


#: Rec.709 <-> linear round-trip via zscale, kept entirely in float (gbrpf32le) so the base is
#: preserved bit-for-bit (an 8-bit intermediate here round-trips the base through ~2 code values and
#: poisons blend's format negotiation). ``setparams`` STAMPS bt709/tv onto the frame first: many
#: consumer clips (and our re-encodes) carry *unspecified* colour tags, on which zscale's ``tin=``
#: hints alone fail with "no path between colorspaces" -- stamping the frame is what makes the
#: linearize robust on any SDR source (after any HDR tonemap the signal is already Rec.709 too).
_LINEARIZE_709 = ("setparams=range=tv:color_primaries=bt709:color_trc=bt709:colorspace=bt709,"
                  "zscale=t=linear:npl=100,format=gbrpf32le")
_ENCODE_709 = "zscale=tin=linear:t=709:m=709:p=bt709:r=tv:npl=100,format=yuv420p"


def ffmpeg_halation_segment(in_label: str, out_label: str, *, strength: float, sigma: float,
                            knee: float = 0.75,
                            red_weight: Sequence[float] = (1.0, 0.35, 0.20),
                            downscale: int = 4) -> str:
    """Filtergraph fragment: red-weighted highlight bloom (HALATION) SCREENED in linear light.

    Mirrors :func:`apply_halation_image`, but as an ffmpeg graph that stays entirely in float
    (``gbrpf32le``) from ONE linearize: force-linearize Rec.709 -> split -> mask highlights with the
    SAME squared soft-knee on linear luminance (``pow(clip((L-knee)/(1-knee),0,1),2)``) computed
    per-pixel via ``geq`` (which is exact on float) + red-weight + Gaussian blur -> ``blend=screen``
    in linear -> back to Rec.709. Keeping the whole op in float preserves the base (no 8-bit
    round-trip) and is a constant per-frame transform => flicker-safe.

    The glow is a heavily blurred low-frequency signal, so it is computed at ``1/downscale``
    resolution (``geq`` cost falls ~``downscale**2``) and ``scale2ref``-upsampled back onto the
    full-res base before the screen -- visually identical to a full-res glow but far cheaper (full-res
    ``geq`` on 1080p is ~4x slower than realtime). ``sigma`` is the blur radius in OUTPUT pixels
    (typically ``0.012*height``); it is scaled to the reduced grid. Intermediate labels are scoped to
    one per-shot graph.
    """
    sr, sg, sb = (float(strength) * float(c) for c in red_weight)
    k = float(knee)
    rng = max(1e-6, 1.0 - k)
    lum = "(0.2126*r(X,Y)+0.7152*g(X,Y)+0.0722*b(X,Y))"
    mask = f"pow(clip(({lum}-{_fg(k)})/{_fg(rng)},0,1),2)"  # squared soft-knee on LINEAR luma
    ds = max(1, int(downscale))
    small_sigma = max(0.6, float(sigma) / ds)
    pre = "" if ds == 1 else f"scale=iw/{ds}:ih/{ds}:flags=area,"  # shrink BEFORE geq -> cheap mask+blur
    return (
        f"[{in_label}]{_LINEARIZE_709},split[halB][halH];"
        f"[halH]{pre}geq=r='r(X,Y)*{mask}':g='g(X,Y)*{mask}':b='b(X,Y)*{mask}',"
        f"colorchannelmixer=rr={_fg(sr)}:gg={_fg(sg)}:bb={_fg(sb)},"
        f"gblur=sigma={_fg(small_sigma)}:steps=2[halGs];"
        f"[halGs][halB]scale2ref=flags=bicubic[halGlow][halB2];"  # upsample glow back onto the base
        f"[halB2][halGlow]blend=all_mode=screen[halScr];"
        f"[halScr]{_ENCODE_709}[{out_label}]"
    )


def ffmpeg_grain_segment(base_label: str, plate_label: str, out_label: str) -> str:
    """Filtergraph fragment: overlay a pre-baked grain plate onto the LUMA plane (monochrome grain).

    Mirrors :func:`apply_grain_image`: Overlay-blend the static plate onto Y only (chroma copied
    through, so the grain is monochrome) weighted toward shadows/mids (``0.605*(1-L)``; highlights
    stay clean). ``scale2ref`` fits the plate to the frame so a small bake-size mismatch can't break
    the blend. ``plate_label`` is the looped grain-plate input pad (e.g. ``"1:v"``). The blend's
    ``A`` is the base, ``B`` the plate (ffmpeg's first input = ``A``).
    """
    overlay = "if(lt(A,128),2*A*B/255,255-2*(255-A)*(255-B)/255)"
    expr = f"A+({overlay}-A)*(0.605*(255-A)/255)"
    # shortest=1: the grain plate is fed as an infinite looped input, so the blend must end when the
    # (finite) base ends -- otherwise framesync's default eof_action=repeat runs forever on a clip
    # with no audio stream to bound it via -shortest.
    return (
        f"[{plate_label}]format=yuv420p[grnP];[{base_label}]format=yuv420p[grnB];"
        f"[grnP][grnB]scale2ref[grnP2][grnB2];"
        f"[grnB2][grnP2]blend=c0_expr='{expr}':c1_expr='A':c2_expr='A':shortest=1[{out_label}]"
    )


def ffmpeg_vignette_segment(base_label: str, mask_label: str, out_label: str) -> str:
    """Filtergraph fragment: multiply a pre-baked elliptical vignette mask in RGB (uniform darken).

    Mirrors :func:`apply_vignette_image`: ``blend=multiply`` of the frame with the mask in RGB
    (``gbrp``) reproduces ``rgb*v`` exactly. ``scale2ref`` fits the mask to the frame.
    ``mask_label`` is the looped vignette-mask input pad (e.g. ``"2:v"``).
    """
    # shortest=1: the mask is fed as an infinite looped input -> end the blend with the finite base
    # (see ffmpeg_grain_segment).
    return (
        f"[{mask_label}]format=gbrp[vigM];[{base_label}]format=gbrp[vigB];"
        f"[vigM][vigB]scale2ref[vigM2][vigB2];"
        f"[vigB2][vigM2]blend=all_mode=multiply:shortest=1,format=yuv420p[{out_label}]"
    )
